development:
  gold_folder: "/Users/chientran/Documents/jaist/test/data/gold"
  system_folder: "/Users/chientran/Documents/jaist/test/data/models"

production:
  gold_folder: "/Users/nguyenlab-imac/chientx/thesis/dailymail_data/web_data/gold"
  system_folder: "/Users/nguyenlab-imac/chientx/thesis/dailymail_data/web_data/models"